auth: &auth
  username: root
  password: 
  host: localhost
  adapter: mysql
  encoding: utf8  

development:
  database: firstapp_development
  <<: *auth

test:
  database: db/test.sqlite3

production:
  database: db/production.sqlite3
